log:
  level: warn
  file: "/tmp/mosdns.log"

plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - _single_flight
        - main_sequence
      server:
        - protocol: udp
          addr: "127.0.0.1:5335"
        - protocol: tcp
          addr: "127.0.0.1:5335"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _return
        - if:
            - query_is_local_domain
            - "!_query_is_common"
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _return
        - primary:
            - forward_local
            - if:
                - "!response_has_local_ip"
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback: 150
          always_standby: true

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "udp://114.114.114.114"
        - addr: "udp://114.114.115.115"
        - addr: "https://223.5.5.5/dns-query"
        - addr: "https://223.6.6.6/dns-query"
        - addr: "https://dns.alidns.com/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "tls://dns.alidns.com"
          idle_timeout: 30
          trusted: true
        - addr: "udp://180.76.76.76"
        - addr: "udp://119.29.29.29"
        - addr: "udp://119.28.28.28"
        - addr: "udp://182.254.116.116"
        - addr: "udp://182.254.118.118"
        - addr: "https://doh.pub/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://sm2.doh.pub/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "tls://dot.pub"
          idle_timeout: 30
          trusted: true
        - addr: "udp://1.2.4.8"
        - addr: "udp://210.2.4.8"

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: "tcp://8.8.8.8"
          idle_timeout: 10
        - addr: "tcp://8.8.4.4"
          idle_timeout: 10
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8:443"
          idle_timeout: 30
          trusted: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8:853"
          idle_timeout: 30
          trusted: true
        - addr: "https://dns.quad9.net/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://doh.opendns.com/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://1.1.1.1/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://1.0.0.1/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1:443"
          idle_timeout: 30
          trusted: true
        - addr: "https://dns.adguard.com/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://doh.dns.sb/dns-query"
          idle_timeout: 30
          trusted: true
        - addr: "https://doh.sb/dns-query"
          idle_timeout: 30
          trusted: true

  - tag: lazy_cache
    type: cache
    args:
      size: 512000
      lazy_cache_ttl: 259200

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "ext:/usr/share/v2ray/geosite.dat:cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "ext:/usr/share/v2ray/geosite.dat:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "ext:/usr/share/v2ray/geoip.dat:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "ext:./serverlist.txt"
        - "ext:/usr/share/v2ray/geosite.dat:category-ads-all"
